controllers:
    resource: ../src/Controller/
    type: attribute

histoire:
    path: /histoire
    controller: App\Controller\HomeController::histoire

alacarte:
    path: /alacarte
    controller: App\Controller\ProductController::alacarte

menudéjeuner:
    path: /menudéjeuner
    controller: App\Controller\LunchMenuController::menudéjeuner

menudiner:
    path: /menudiner
    controller: App\Controller\DinnerMenuController::menudiner

reservation:
    path: /reservation
    controller: App\Controller\ReservationController::reservation

accescontact:
    path: /accescontact
    controller: App\Controller\HomeController::accescontact

login:
    path: /login
    controller: App\Controller\SecurityController::login

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::inscription


reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::reset-password

instagram:
    path: /instagram
    controller: App\Controller\HomeController::instagram

facebook:
    path: /facebook
    controller: App\Controller\HomeController::facebook

moncompte:
    path: /moncompte
    controller: App\Controller\UserController::moncompte


edituser:
    path: /edituser
    controller: App\Controller\EditUserController::edituser


confirmdeletemoncompte:
    path: /confirmdeletemoncompte
    controller: App\Controller\UserController::confirmdeletemoncompte


deletemoncompte:
    path: /deletemoncompte/{id}
    controller: App\Controller\UserController::deletemoncompte

askreservation:
    path: /askreservation
    controller: App\Controller\HomeController::askreservation

cardproducts:
    path: /cardproducts
    controller: App\Controller\AdminController::cardproducts

menus:
    path: /menus
    controller: App\Controller\AdminController::menus

reservations:
    path: /reservations
    controller: App\Controller\AdminController::reservations

clients:
    path: /clients
    controller: App\Controller\AdminController::clients

pictures:
    path: /pictures
    controller: App\Controller\AdminController::pictures

admins:
    path: /admins
    controller: App\Controller\AdminController::admins

categories:
    path: /categories
    controller: App\Controller\AdminController::categories

hours:
    path: /hours
    controller: App\Controller\AdminController::hours

