controllers:
    resource: ../src/Controller/
    type: attribute

histoire:
    path: /histoire
    controller: App\Controller\HomeController::histoire

alacarte:
    path: /alacarte
    controller: App\Controller\ProductController::alacarte

menudéjeuner:
    path: /menudéjeuner
    controller: App\Controller\LunchMenuController::menudéjeuner

menudiner:
    path: /menudiner
    controller: App\Controller\DinnerMenuController::menudiner

reservation:
    path: /reservation
    controller: App\Controller\ReservationController::reservation

accescontact:
    path: /accescontact
    controller: App\Controller\HomeController::accescontact

login:
    path: /login
    controller: App\Controller\SecurityController::login

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::inscription


instagram:
    path: /instagram
    controller: App\Controller\HomeController::instagram

facebook:
    path: /facebook
    controller: App\Controller\HomeController::facebook

moncompte:
    path: /moncompte
    controller: App\Controller\UserController::moncompte


edituser:
    path: /edituser
    controller: App\Controller\EditUserController::edituser


confirmdeletemoncompte:
    path: /confirmdeletemoncompte
    controller: App\Controller\UserController::confirmdeletemoncompte


deletemoncompte:
    path: /deletemoncompte/{id}
    controller: App\Controller\UserController::deletemoncompte

askreservation:
    path: /askreservation
    controller: App\Controller\HomeController::askreservation

products:
    path: /admin/products
    controller: App\Controller\ProductsController::products

menus:
    path: /admin/menus
    controller: App\Controller\MenusController::menus

reservations:
    path:  /admin/reservations
    controller: App\Controller\ReservationsController::reservations

newreservations:
    path:  /admin/newreservations
    controller: App\Controller\ReservationsController::newreservations

editreservations:
    path:  /admin/editreservations/{id}
    controller: App\Controller\ReservationsController::editreservations

deletereservations:
    path:  /admin/deletereservations/{id}
    controller: App\Controller\ReservationsController::deletereservations

users:
    path: /admin/users
    controller: App\Controller\UsersController::users

newusers:
    path: /admin/newusers
    controller: App\Controller\UsersController::newusers

editusers:
    path:  /admin/editusers/{id}
    controller: App\Controller\UsersController::editusers

deleteusers:
    path:  /admin/deleteusers/{id}
    controller: App\Controller\UsersController::deleteusers


pictures:
    path: /admin/pictures
    controller: App\Controller\PicturesController::pictures

newpictures:
    path: /admin/newpictures
    controller: App\Controller\PicturesController::newpictures

editpictures:
    path: /admin/editpictures/{id}
    controller: App\Controller\PicturesController::editpictures

deletepictures:
    path: /admin/deletepictures/{id}
    controller: App\Controller\PicturesController::deletepictures


administrators:
    path: /admin/administrators
    controller: App\Controller\AdminController::administrators

newadministrators:
    path: /admin/newadministrators
    controller: App\Controller\AdminController::newadministrators

editadministrators:
    path: /admin/editadministrators/{id}
    controller: App\Controller\AdminController::editadministrators

deleteadministrators:
    path: /admin/deleteadministrators/{id}
    controller: App\Controller\AdminController::deleteadministrators


categories:
    path: /admin/categories
    controller: App\Controller\CategoriesController::categories

newcategories:
    path: /admin/newcategories
    controller: App\Controller\CategoriesController::newcategories

editcategories:
    path: /admin/editcategories/{id}
    controller: App\Controller\CategoriesController::editcategories

deletecategories:
    path: /admin/deletecategories/{id}
    controller: App\Controller\CategoriesController::deletecategories

hours:
    path: /admin/hours
    controller: App\Controller\HoursController::hours

newhours:
    path: /admin/newhours
    controller: App\Controller\HoursController::newhours

edithours:
    path: /admin/edithours/{id}
    controller: App\Controller\HoursController::edithours

deletehours:
    path: /admin/deletehours/{id}
    controller: App\Controller\HoursController::deletehours


admin:
    path: /admin
    controller: App\Controller\AdminController::admin

createmenus:
    path: /admin/createmenus
    controller: App\Controller\MenusController::createmenus

newmenus:
    path: /admin/newmenus
    controller: App\Controller\MenusController::newmenus

editmenus:
    path: /admin/editmenus/{id}
    controller: App\Controller\MenusController::editmenus

deletemenus:
    path: /admin/deletemenus/{id}
    controller: App\Controller\MenusController::deletemenus

newproducts:
    path: /admin/newproducts
    controller: App\Controller\ProductsController::newproducts

editproducts:
    path: /admin/editproducts/{id}
    controller: App\Controller\ProductsController::editproducts

deleteproducts:
    path: /admin/deleteproducts/{id}
    controller: App\Controller\ProductsController::deleteproducts


newproductmenus:
    path: /admin/newproductmenus
    controller: App\Controller\MenusController::newproductmenus

editproductmenus:
    path: /admin/editproductmenus/{id}
    controller: App\Controller\MenusController::editproductmenus

deleteproductmenus:
    path: /admin/deleteproductmenus/{id}
    controller: App\Controller\MenusController::deleteproductmenus

availability:
    path: /availability
    controller: App\Controller\AvailabilityController::availability
