controllers:
    resource: ../src/Controller/
    type: attribute

histoire:
    path: /histoire
    controller: App\Controller\HomeController::histoire

alacarte:
    path: /alacarte
    controller: App\Controller\ProductController::alacarte

menudéjeuner:
    path: /menudéjeuner
    controller: App\Controller\LunchMenuController::menudéjeuner

menudiner:
    path: /menudiner
    controller: App\Controller\DinnerMenuController::menudiner

reservation:
    path: /reservation
    controller: App\Controller\ReservationController::reservation

accescontact:
    path: /accescontact
    controller: App\Controller\HomeController::accescontact

login:
    path: /login
    controller: App\Controller\SecurityController::login

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::inscription


reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::reset-password

instagram:
    path: /instagram
    controller: App\Controller\HomeController::instagram

facebook:
    path: /facebook
    controller: App\Controller\HomeController::facebook

moncompte:
    path: /moncompte
    controller: App\Controller\UserController::moncompte


edituser:
    path: /edituser
    controller: App\Controller\EditUserController::edituser


confirmdeletemoncompte:
    path: /confirmdeletemoncompte
    controller: App\Controller\UserController::confirmdeletemoncompte


deletemoncompte:
    path: /deletemoncompte/{id}
    controller: App\Controller\UserController::deletemoncompte

askreservation:
    path: /askreservation
    controller: App\Controller\HomeController::askreservation

products:
    path: /admin/products
    controller: App\Controller\ProductsController::products

menus:
    path: /admin/menus
    controller: App\Controller\MenusController::menus

reservations:
    path:  /admin/reservations
    controller: App\Controller\ReservationsController::reservations

newreservations:
    path:  /admin/newreservations
    controller: App\Controller\ReservationsController::newreservations

editreservations:
    path:  /admin/editreservations/{id}
    controller: App\Controller\ReservationsController::editreservations

deletereservations:
    path:  /admin/deletereservations/{id}
    controller: App\Controller\ReservationsController::deletereservations

users:
    path: /admin/users
    controller: App\Controller\UsersController::users

pictures:
    path: /admin/pictures
    controller: App\Controller\PicturesController::pictures

administrators:
    path: /admin/administrators
    controller: App\Controller\AdminController::administrators

categories:
    path: /admin/categories
    controller: App\Controller\CategoriesController::categories

hours:
    path: /admin/hours
    controller: App\Controller\HoursController::hours

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

createmenus:
    path: /admin/createmenus
    controller: App\Controller\MenusController::createmenus

newmenus:
    path: /admin/newmenus
    controller: App\Controller\MenusController::newmenus

editmenus:
    path: /admin/editmenus/{id}
    controller: App\Controller\MenusController::editmenus

deletemenus:
    path: /admin/deletemenus/{id}
    controller: App\Controller\MenusController::deletemenus

newproducts:
    path: /admin/newproducts
    controller: App\Controller\ProductsController::newproducts

editproducts:
    path: /admin/editproducts/{id}
    controller: App\Controller\ProductsController::editproducts

deleteproducts:
    path: /admin/deleteproducts/{id}
    controller: App\Controller\ProductsController::deleteproducts


newproductmenus:
    path: /admin/newproductmenus
    controller: App\Controller\MenusController::newproductmenus

editproductmenus:
    path: /admin/editproductmenus/{id}
    controller: App\Controller\MenusController::editproductmenus

deleteproductmenus:
    path: /admin/deleteproductmenus/{id}
    controller: App\Controller\MenusController::deleteproductmenus
